import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className='main-header'>
        <ul>
          <li><Link href="/">홈</Link></li>
          <li><Link href="/list">리스트</Link></li>
          <li><Link href="/list/check">홈</Link></li>
        </ul>
      </div>
      {children}      
    </html>
  )
}
